# Generated by Django 4.2.24 on 2025-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaridade',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
