# Generated by Django 4.2.24 on 2025-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_escolaridade_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experienciaproficional',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
